cod 177 run time based benchmarks in the codspeed runner
CodSpeedHQ/runner pull request #39
Opened 2024-09-17 13:33 UTC by adriencaccia

- **refactor(runner): create executor instrument abstraction and add ValgrindInstrument**
- **feat(runner): add WallTimeInstrument**
- **feat(runner): add cpu and memory data to SytemInfo**

2024-09-17 16:06 UTC, fargito commented on src/run/runner/helpers/run_command_with_log_pipe.rs
> +        .stderr(std::process::Stdio::piped())
Do we redirect stderr to stdin because of a Github actions runner specificity?

2024-09-17 16:06 UTC, fargito commented on src/run/runner/valgrind/measure.rs
> +            setup_introspected_node()
```suggestion
            setup_introspected_nodejs()
```
Maybe a little bit more explicit

2024-09-17 17:10 UTC, art049 requested changes
I think we need to refactor a bit the executor instrument and even if it might be a big change right now we can keep it for the future instruments

2024-09-17 17:10 UTC, art049 commented on src/run/check_system.rs
> +            total_memory_gb: ram_quantity,
this could be named `total_memory_gb` directly

2024-09-17 17:10 UTC, art049 commented on src/run/runner/valgrind/instrument.rs
> +        Ok(())
A lot of this logic should not be directly here and should probably be relocated to `src/run/mod.rs` if we want to make an abstract executor(and then reuse most of the logic we already have for another instrument)

- the groups for should be managed outside of the executor
- we should create a dedicated setup method in the executor
- the executor itself should not start/stop the other instruments

2024-09-17 17:10 UTC, art049 commented on src/run/runner/mod.rs
> +    if ValgrindInstrument::detect() {
I think this `ExecutorInstrumentDetector` trait is overkill. For now, we have at most two executor instruments having the logic here or in `src/run/mod.rs` would be simpler

2024-09-17 17:10 UTC, art049 commented on src/run/runner/executor_instrument.rs
> +    }
In my opinion, this logic should be directly in `src/run/mod.rs`
The difference between run and run_executor is not super easy to understand. I think we shouldn't use the trait system to share code in our case, but we should prefer our parent function calling the executor

2024-09-17 17:10 UTC, art049 commented on src/run/runner/mod.rs
> +}
This could be a trait variable in each instrument

2024-09-18 08:22 UTC, adriencaccia commented on src/run/runner/helpers/run_command_with_log_pipe.rs
> +        .stderr(std::process::Stdio::piped())
We redirect both stdout and stderr to the logger, and it's up to the logger to decide what to do with the logs. We have a logger for each `ci_provider` (GitHub Actions, Buildkite, and the local provider).

2024-09-18 14:30 UTC, art049 approved these changes

2024-09-18 14:30 UTC, art049 commented on src/run/runner/mod.rs
> +        Ok(_) => bail!("Unknown codspeed runner mode"),
maybe more simple is possible here

2024-09-18 14:49 UTC, merged