feat(gitlab): add gitlab support
CodSpeedHQ/runner pull request #47
Opened 2024-10-24 13:21 UTC by fargito

2024-10-29 13:06 UTC, fargito commented on .gitlab-ci.yml
Needs to be removed

2024-11-04 08:05 UTC, adriencaccia requested changes
👏

2024-11-04 08:05 UTC, adriencaccia commented on .vscode/settings.json
> +    "editor.inlayHints.enabled": "offUnlessPressed"
This setting is personal, we can remove it

2024-11-04 08:05 UTC, adriencaccia commented on src/run/ci_provider/github_actions/provider.rs
> +                id: get_env_variable("GITHUB_ACTOR_ID")?,
👍

2024-11-04 08:05 UTC, adriencaccia commented on src/run/ci_provider/interfaces.rs
> +    Github,
```suggestion
    GitLab,
    GitHub,
```

2024-11-04 08:05 UTC, adriencaccia commented on src/run/ci_provider/gitlab_ci/logger.rs
> +    static ref GITLAB_SECTION_ID_REGEX: Regex =
The name of this regex does not describe its purpose, maybe something like `GITLAB_SECTION_ID_SANITIZE_REGEX`

2024-11-04 08:05 UTC, adriencaccia commented on src/run/ci_provider/gitlab_ci/logger.rs
> +            }
It would be better to have the color codes in variables, instead of having to look at the linked gist

2024-11-04 14:02 UTC, adriencaccia approved these changes
LGTM, waiting on @art049

2024-11-06 09:07 UTC, art049 reviewed
WIP review

2024-11-06 09:07 UTC, art049 commented on src/run/check_system.rs
> +            ("Debian GNU/Linux", "12", "x86_64"),
What is different here? Why do we need to define a new entry?

2024-11-06 09:07 UTC, art049 commented on src/run/ci_provider/gitlab_ci/logger.rs
> +
We should use a library instead, like: https://github.com/CodSpeedHQ/runner/blob/1d9a505e87631e5e71eefb8f80e53ca95e2d8283/src/auth.rs#L45-L51

2024-11-06 09:07 UTC, art049 commented on .vscode/settings.json
> +  ]
can we put that into a separate json file as we have in our monorepo setup?

2024-11-06 09:23 UTC, fargito commented on src/run/check_system.rs
> +            ("Debian GNU/Linux", "12", "x86_64"),
This is the way it is set by GitlabCI

2024-11-06 09:52 UTC, fargito commented on src/run/check_system.rs
> +            ("Debian GNU/Linux", "12", "x86_64"),
Do you think I should reformat it?

2024-11-06 15:14 UTC, art049 requested changes
Looking forward to see how the color stuff we discussed will end up being

2024-11-06 15:14 UTC, art049 commented on src/run/check_system.rs
> +            ("Debian GNU/Linux", "12", "x86_64"),
as discussed it would be great to use `distribution_id` from SystemInfo

2024-11-06 15:14 UTC, art049 commented on src/run/runner/valgrind/setup.rs
> +        | ("Debian GNU/Linux", "12", "x86_64") => ("20.04", "amd64"),
maybe here as well we can use distribution id

2024-11-06 15:36 UTC, art049 approved these changes

2024-11-12 15:15 UTC, merged